### PR TITLE
Ergonomic refactor

### PR DESCRIPTION
**Pull request by troopa81**
This PR implements modification described in issue #14 

Contrary of what was previously described: 
- There is not a unique dockable window but you get a window for the current active layer (same behavior than the attribute table)
- The visibility is not managed with checkboxes but still with + and - buttons. I think it will better to have an organize column like the one in attribute table where you can configure the visibility and order of your columns. You could also add new column from this widget.
- Column order aren't saved in project
- You can select one or several feature to be displayed in the widget. It replace the "select an other feature" functionnality available from data_selector
**EDIT**
- You can also add a plot configurtion and save it to your project 

qgeologis_add_plot

All other existing features are supposedly still working. However there is a problem with the configuration of timeseries named `Cote de nappe (mesures manuelles)` , it crashes QGIS.

Sorry for the size of the PR...

### CODE REVIEW

**Comment by mhugo** [comment]
> You can select one or several feature to be displayed in the widget. It replace the "select an other feature" functionnality available from data_selector

Is the multi selection implemented or not ?

> However there is a problem with the configuration of timeseries named Cote de nappe (mesures manuelles) , it crashes QGIS.

Any clue ?

**Comment by troopa81** [comment]
> Is the multi selection implemented or not ?

Yes

>> However there is a problem with the configuration of timeseries named Cote de nappe (mesures manuelles) , it crashes QGIS.
>
> Any clue ?

My first guess was that the coordinate generated from the data were too
huge but I try a quick fix and it doesn't work. Or maybe it's because of
instantenous timeseries (Actually, chemical measures seem to have the
same problem).

It crashes here https://github.com/troopa81/QGIS/blob/multithreads_tests/src/core/symbology/qgsmarkersymbollayer.cpp#L1020

**Comment by troopa81** [comment]
I complete the PR with new feature, the ability to add a plot configuration and save it to your QGIS project. 

qgeologis_add_plot
 
cc @vmora

**Comment by mhugo** [comment]
@troopa81 Good job !

First quick review:

Pros:
- I like the unique dockable window that behaves like the attribute table
- Adding a new data source with the configuration dialog is a good idea

Cons / Not sure:
- The configuration refers to layers by their id inside the QGIS project. However, I am not sure I want to expose all the different layers to the final user. Refering layers by a pair (source, provider) and loading them if they are not in the project seems a good alternative.
- Actually, I am not sure I want to store the configuration in a QGIS project. That should be a nice option to have, but not the primary way of storing the configuration.
- I've encountered some rendering issues and crashes, probably linked to the display of image data (?)
- It is really not clear what is the "starting" state of displays when you select a feature. Apparently it displays **all** defined curves and then you can delete / reload some of them. I think that what you mentioned above. Visibility checkboxes should be better.

I'll then create a branch and work on some of these issues before merging into master

**Comment by mhugo** [comment]
@troopa81 Regarding my main concerns, and after some more thoughts, I think the following additional tasks would make the plugin usable for the different use cases we have :
- first, make references to data sources in the configuration using (URI, provider) rather than by layer id so that they can be stored outside of the QGIS project
- then add functions to import the configuration from a plain file and a function to export the configuration to a plain file as well

**Comment by mhugo** [comment]
@troopa81 After some more testing and considerations:
- my main concern about storing the configuration in a project file is probably not that bad after all :)
- I've fixed a bug or two when plots were drawn very far away from the current view

I've worked in the branch https://github.com/Oslandia/QGeoloGIS/tree/ergonomic_refactor

I will then merge it into master. I close this ticket.

Thanks !

**Pull request closed without merging**
