### PR TITLE
adds min and max config for continuous and instantaneous plots

### PR DESCRIPTION
**Pull request by vmora**

### CODE REVIEW

**Comment by vmora** [comment]
I see that plots are from from a position and interval, with albion I have a 'to_' and 'from_' column and it doesn't work, could we have an option for that ?

This branch kinda works, but I think there is a bug when adding new column, can you check that @mhugo before merging ? Thanks

**Comment by mhugo** [comment]
> I see that plots are from from a position and interval, with albion I have a 'to_' and 'from_' column and it doesn't work, could we have an option for that ?

Not sure to understand. Depth ranges of stratigraphic logs are defined by two fields "depth_from" and "depth_to", which seems to fit your usecase. For other kind of graphs, there are two storage modes (names are not well chosen):
- "continuous" : data defined by continuous "blocks" with a start and an array of data
- "instantaneous": data defined by one (x, y) value for each sample, which seems to fit your need here.

Did I miss something else ?

I'll have a look at your branch, thanks

**Comment by mhugo** [comment]
I fixed a bug to make it work.

We should quickly add a way to update the configuration of a column !

**Comment by vmora** [comment]
Thanks a lot @mhugo

**Pull request merged**
